TypeScript笔记
toimc-team/front-end-notes pull request #4
Opened 2021-04-26 12:16 UTC by luckyjolly

2021-04-28 11:22 UTC, toimc requested changes
- [ ] 目录结构需要调整
- [ ] 内容进一步完善
- [ ] 清晰的引用

2021-04-28 11:22 UTC, toimc commented on src/basic/ts/README.md
> +多看别人的定义文件，尤其是大项目的。
这里可以引用几个你觉得比较优秀的案例吗？

2021-04-28 11:22 UTC, toimc commented on src/basic/ts/README.md
> +## 知识点总结
可以使用[vuepres目录](https://vuepress.vuejs.org/zh/guide/markdown.html#%E7%9B%AE%E5%BD%95)，把这一块放置在最前面，按照这个目录，展开笔记的内容。

2021-04-28 11:22 UTC, toimc commented on src/basic/ts/README.md
> +```typescript
不建议在danger这种类型的提示中，再加入代码块，非常不友好

2021-04-28 11:22 UTC, toimc commented on src/basic/ts/README.md
> +### 类和接口
interface与type有使用场景的区别，[参考](https://juejin.cn/post/6844903749501059085)

2021-05-01 05:57 UTC, closed without merging

2021-05-01 05:58 UTC, luckyjolly commented
其他同学写的更好

2021-05-01 11:11 UTC, toimc commented
@luckyjolly 没关系，可以一起来完善，重要是的参与进来。与自己比较~~